# Generated by Django 5.2.3 on 2025-11-16 16:00

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DGC Engineering Sarl', max_length=200)),
                ('address', models.TextField(default='TVZ- NDB Street - University zone 0321')),
                ('city', models.CharField(default='Nouakchott', max_length=100)),
                ('country', models.CharField(default='Mauritania', max_length=100)),
                ('phone', models.CharField(default='+222 33 35 93 33', max_length=20)),
                ('email', models.EmailField(default='info@dgc.mr', max_length=254)),
                ('nif', models.CharField(default='00718015', help_text='Tax Identification Number', max_length=50, verbose_name='NIF')),
                ('bank_name', models.CharField(default='BPM', max_length=200)),
                ('account_number', models.CharField(default='1004497', max_length=100)),
                ('bank_code', models.CharField(blank=True, default='DGC - EG', max_length=50)),
                ('default_currency', models.CharField(default='MRU', max_length=10)),
                ('default_tva_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default TVA/VAT rate in percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('department', models.CharField(blank=True, default='Commercial Dept', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, help_text='City or location', max_length=300)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, help_text='Full address')),
                ('tax_id', models.CharField(blank=True, help_text='Customer Tax Identification Number', max_length=100, verbose_name='NIF/Tax ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('quotation', 'Quotation'), ('invoice', 'Invoice')], default='quotation', help_text='Type of document', max_length=20)),
                ('reference', models.CharField(help_text='Auto-generated: QT-YY-MM-XXX or IN-YY-MM-XXX', max_length=50, unique=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('customer_name', models.CharField(help_text='Customer name (required)', max_length=200)),
                ('customer_location', models.CharField(blank=True, max_length=300)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_po_ref', models.CharField(blank=True, help_text="Customer's Purchase Order reference (for invoices)", max_length=100, verbose_name='Customer PO Reference')),
                ('work_delivery', models.TextField(blank=True, help_text='Delivery terms (quotations only)', verbose_name='Work Delivery Terms')),
                ('payment_terms', models.TextField(blank=True, help_text='Payment conditions (quotations only)', verbose_name='Payment Terms')),
                ('currency', models.CharField(choices=[('MRU', 'MRU - Mauritanian Ouguiya'), ('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro')], default='MRU', max_length=10)),
                ('tva_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate in percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='TVA Rate (%)')),
                ('amount_in_words', models.TextField(blank=True, help_text='Amount written in words (invoices only)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not shown on document)')),
                ('footer_text', models.TextField(blank=True, help_text='Additional text for document footer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL)),
                ('converted_to_invoice', models.OneToOneField(blank=True, help_text='Invoice created from this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotation', to='Invoice.document')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Link to customer database (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='Invoice.customer')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('status_changed', 'Status Changed'), ('converted', 'Converted to Invoice')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, help_text='Additional details about the change')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Invoice.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Document Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveIntegerField(help_text='Line item number (auto-generated)')),
                ('description', models.TextField(help_text='Description of the item/service')),
                ('unit', models.CharField(choices=[('PC', 'PC'), ('Unit', 'Unit'), ('Hour', 'Hour'), ('Day', 'Day'), ('Month', 'Month'), ('Set', 'Set'), ('Box', 'Box'), ('Kg', 'Kg'), ('Meter', 'Meter'), ('Liter', 'Liter')], default='PC', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Invoice.document')),
            ],
            options={
                'ordering': ['item_number'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='Invoice_cus_name_7e2808_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='Invoice_cus_is_acti_403b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-date'], name='Invoice_doc_date_f577c2_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='Invoice_doc_status_0675d9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='Invoice_doc_documen_72a07b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['reference'], name='Invoice_doc_referen_08d2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['customer'], name='Invoice_doc_custome_73bb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='documenthistory',
            index=models.Index(fields=['document', '-timestamp'], name='Invoice_doc_documen_802811_idx'),
        ),
        migrations.AddIndex(
            model_name='documentitem',
            index=models.Index(fields=['document', 'item_number'], name='Invoice_doc_documen_dbe85a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentitem',
            unique_together={('document', 'item_number')},
        ),
    ]
